kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: amd64
steps:
- name: deploy
  image: docker.io/kameshsampath/drone-vercel-plugin
  pull: never
  settings:
    log_level: debug
    # valid values are production, development, preview
    vercel_env: production
    vercel_token:
      from_secret: vercel_token
    vercel_org_id:
      from_secret: vercel_org_id
    vercel_project_id:
      from_secret: vercel_project_id
    vercel_project_create: true
    vercel_environment:
    - NEXT_PUBLIC_FOO=BAR
    - NEXT_PUBLIC_XMAS=25 Dec
