kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: amd64
steps:
- name: deploy
  image: docker.io/kameshsampath/drone-vercel-deploy
  pull: never
  settings:
    vercel_token:
      from_secret: vercel_token
    vercel_org_id:
      from_secret: vercel_org_id
    vercel_project_id:
      from_secret: vercel_project_id
    vercel_project_create: true
    # valid values are development, preview,production
    vercel_environment: development
    vercel_environment_variables:
    - NEXT_PUBLIC_FOO=BAR
    - NEXT_PUBLIC_XMAS=25 Dec
    log_level: debug
